apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
        - name: backend
          image: nitishnandan/backend:latest
          ports:
            - containerPort: 3000
        - name: frontend
          image: nitishnandan/frontend:latest
          ports:
            - containerPort: 3000
