apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue  # Switch to "green" when needed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
